---
fullname: ABS Metatheory
shortname: abs-metatheory
organization: kth-step
community: false
action: true
dune: true

synopsis: Formal metatheory in Coq of the ABS language

description: |-
  Formal metatheory in Coq for the ABS language.

publications:
- pub_url: https://link.springer.com/chapter/10.1007/978-3-642-25271-6_8
  pub_title: 'ABS: A Core Language for Abstract Behavioral Specification'
  pub_doi: 10.1007/978-3-642-25271-6_8

authors:
- name: Åsmund Kløvstad
- name: Karl Palmskog

opam-file-maintainer: palmskog@gmail.com

opam-file-version: dev

license:
  fullname: MIT License
  identifier: MIT

supported_coq_versions:
  text: 8.18 or later
  opam: '{>= "8.18"}'

dependencies:
- opam:
    name: coq-ott
    version: '{>= "0.33"}'
  description: |-
    [Ott Coq library](https://github.com/ott-lang/ott) 0.33 or later
- opam:
    name: coq-equations
    version: '{>= "1.3"}'
  description: |-
    [Equations Coq library](https://github.com/mattam82/Coq-Equations) 1.3 or later
- opam:
    name: coq-stdpp
    version: '{>= "1.9.0"}'
  description: |-
    [Coq-Std++](https://gitlab.mpi-sws.org/iris/stdpp) 1.9.0 or later

tested_coq_opam_versions:
- version: '8.19'
- version: '8.18'

namespace: ABS

keywords:
- name: ABS

categories:
- name: Computer Science/Semantics and Compilation/Semantics

build: |-
  ## Building instructions

  To install all dependencies, do:
  
  ```shell
  opam repo add coq-released https://coq.inria.fr/opam/released
  opam install coq.8.19.2 coq-ott coq-equations coq-stdpp
  ```
  
  To build when dependencies are installed, do:
  ```shell
  git clone https://github.com/kth-step/abs-metatheory.git
  cd abs-metatheory
  make   # or make -j <number-of-cores-on-your-machine> 
  ```

  To build a pdf documenting the project, ensure that `ott` and
  TeX Live (`pdflatex`) are installed, and do:
  ```shell
  make docs/report/main.pdf
  ```
  Note that the source file to edit for this pdf is `docs/report/main.mng`.

documentation: |-
  ## Documentation

  - [latest technical report](https://kth-step.github.io/abs-metatheory/docs/report/main.pdf)
  - [latest coqdoc documentation](https://kth-step.github.io/abs-metatheory/docs/coqdoc/toc.html)

  See also [ABS Tools](https://github.com/abstools/abstools).
---
